### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by marvinhagemeister** [moovweb/react-storefront-boilerplate#85]
Just cloned the repo, did an `npm install` followed by `npm start` and I was expecting the app to start, but was greeted with the following error:

```txt
$ npm start

> react-storefront-boilerplate@4.0.0 link /home/marvinh/dev/test/react-storefront-boilerplate
> f() { ln -sf moov_config-$@.json moov_config.json; }; f "local"

[2020-10-06T19:27:09.359Z]  info: MoovJS SDK 7.2.0 is starting
[2020-10-06T19:27:09.360Z]  info: Starting with arguments:
[2020-10-06T19:27:09.360Z]  info: - path: /home/marvinh/dev/test/react-storefront-boilerplate (default: /home/marvinh/dev/test/react-storefront-boilerplate)
[2020-10-06T19:27:09.360Z]  info: - upstream: null (default: contents of moov_config.json)
[2020-10-06T19:27:09.360Z]  info: - port: 8080 (default: 8080)
[2020-10-06T19:27:09.360Z]  info: - pretend-ssl: true (default: true)
[2020-10-06T19:27:09.361Z]  info: - timeout: 60 seconds (default: 60)
[2020-10-06T19:27:09.361Z]  info: - log-level: info (default: info)
[2020-10-06T19:27:09.361Z]  info: - user-console-level: log (default: log)
[2020-10-06T19:27:09.361Z]  info: - host-hack: false (default: false)
[2020-10-06T19:27:09.361Z]  info: - replay-upstream-requests: false (default: false)
[2020-10-06T19:27:09.361Z]  info: - record-upstream-requests: false (default: true)
[2020-10-06T19:27:09.361Z]  info: - max-recorded-requests: 200 (default: 200)
[2020-10-06T19:27:09.368Z]  info: No other instances of Moov CLI with the same base port were detected.
[2020-10-06T19:27:09.370Z]  info: Pausing requests before first build finishes
[2020-10-06T19:27:09.376Z]  info: Starting on_start task as configured in moov_config
[2020-10-06T19:27:10.045Z]  task: Starting server rebundle...
[2020-10-06T19:27:10.045Z]  info: MoovJS SDK is running
[2020-10-06T19:27:10.056Z]  task: Starting client rebundle...
[2020-10-06T19:27:10.105Z]  task: fs.js:36
[2020-10-06T19:27:10.105Z]  task: } = primordials;
[2020-10-06T19:27:10.106Z]  task:     ^
[2020-10-06T19:27:10.106Z]  task: ReferenceError: primordials is not defined
[2020-10-06T19:27:10.106Z]  task:     at fs.js:36:5
[2020-10-06T19:27:10.106Z]  task:     at req_ (/home/marvinh/dev/test/react-storefront-boilerplate/node_modules/natives/index.js:143:24)
[2020-10-06T19:27:10.106Z]  task:     at Object.req [as require] (/home/marvinh/dev/test/react-storefront-boilerplate/node_modules/natives/index.js:55:10)
[2020-10-06T19:27:10.106Z]  task:     at Object.<anonymous> (/home/marvinh/dev/test/react-storefront-boilerplate/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
[2020-10-06T19:27:10.106Z]  task:     at Module._compile (internal/modules/cjs/loader.js:1137:30)
[2020-10-06T19:27:10.107Z]  task:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
[2020-10-06T19:27:10.107Z]  task:     at Module.load (internal/modules/cjs/loader.js:985:32)
[2020-10-06T19:27:10.107Z]  task:     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
[2020-10-06T19:27:10.107Z]  task:     at Module.require (internal/modules/cjs/loader.js:1025:19)
[2020-10-06T19:27:10.107Z]  task:     at require (internal/modules/cjs/helpers.js:72:18)
[2020-10-06T19:27:10.107Z]  task:     at Object.<anonymous> (/home/marvinh/dev/test/react-storefront-boilerplate/node_modules/vinyl-fs/node_modules/graceful-fs/graceful-fs.js:3:27)
[2020-10-06T19:27:10.107Z]  task:     at Module._compile (internal/modules/cjs/loader.js:1137:30)
[2020-10-06T19:27:10.107Z]  task:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
[2020-10-06T19:27:10.107Z]  task:     at Module.load (internal/modules/cjs/loader.js:985:32)
[2020-10-06T19:27:10.108Z]  task:     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
[2020-10-06T19:27:10.108Z]  task:     at Module.require (internal/modules/cjs/loader.js:1025:19)
[2020-10-06T19:27:10.113Z] error: Task on_start exited, restarting it (code: 1)
[2020-10-06T19:27:10.114Z]  info: Starting on_start task as configured in moov_config
[2020-10-06T19:27:10.779Z]  task: Starting server rebundle...
[2020-10-06T19:27:10.790Z]  task: Starting client rebundle...
[2020-10-06T19:27:10.838Z]  task: fs.js:36
[2020-10-06T19:27:10.838Z]  task: } = primordials;
[2020-10-06T19:27:10.838Z]  task:     ^
[2020-10-06T19:27:10.839Z]  task: ReferenceError: primordials is not defined
[2020-10-06T19:27:10.839Z]  task:     at fs.js:36:5
[2020-10-06T19:27:10.839Z]  task:     at req_ (/home/marvinh/dev/test/react-storefront-boilerplate/node_modules/natives/index.js:143:24)
[2020-10-06T19:27:10.839Z]  task:     at Object.req [as require] (/home/marvinh/dev/test/react-storefront-boilerplate/node_modules/natives/index.js:55:10)
[2020-10-06T19:27:10.839Z]  task:     at Object.<anonymous> (/home/marvinh/dev/test/react-storefront-boilerplate/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
[2020-10-06T19:27:10
```

Happens with both Node 12 and Node 14.

**Comment by kevhender** [comment]
Hi @marvinhagemeister, thanks for your report. Please be advised that this repo is a boilerplate repo for a retired version of React Storefront (RSF 6). The latest version of RSF is [version 8](https://github.com/storefront-foundation/react-storefront), and the project is now maintained by the [Storefront Foundation](https://www.reactstorefront.io/).  The updated docs for RSF 8 are located at https://docs.reactstorefront.io/. You should follow the instructions there to get started with this version.
